def get_content():
    return {
        "id": "T1070.008",
        "url_id": "T1070/008",
        "title": "Indicator Removal: Clear Mailbox Data",
        "description": "Adversaries may modify mail and mail application data to remove evidence of their activity. Email applications allow users and other programs to export and delete mailbox data via command line tools or use of APIs. Mail application data can be emails, email metadata, or logs generated by the application or operating system, such as export requests.",
        "tags": ["defense evasion", "email", "mailbox", "exchange", "powershell", "linux", "macos", "windows"],
        "tactic": "defense-evasion",
        "protocol": "",
        "os": "Windows, Linux, macOS, Office Suite",
        "tips": [
            "Monitor mailbox export, delete, and cleanup activity",
            "Audit use of PowerShell mail commands like Remove-MailboxExportRequest",
            "Look for command-line use of 'mail' or 'mailx' on Linux/macOS"
        ],
        "data_sources": "Application Log, Command, File, Process",
        "log_sources": [
            {"type": "Application Log", "source": "", "destination": ""},
            {"type": "Command", "source": "", "destination": ""},
            {"type": "File", "source": "", "destination": ""},
            {"type": "Process", "source": "", "destination": ""}
        ],
        "source_artifacts": [
            {"type": "File", "location": "C:\\Program Files\\Microsoft\\Exchange Server\\V15\\Logging\\", "identify": "Exchange mailbox export logs"},
            {"type": "Application Log", "location": "Event Viewer > Applications and Services Logs > MSExchange", "identify": "PowerShell cmdlet activity"},
            {"type": "Command", "location": "/usr/bin/mail", "identify": "Use of 'mail' or 'mailx' for deletion"},
            {"type": "File", "location": "~/Library/Mail", "identify": "macOS local mail store"}
        ],
        "destination_artifacts": [
            {"type": "", "location": "", "identify": ""}
        ],
        "detection_methods": [
            "Alert on execution of Remove-MailboxExportRequest or similar PowerShell cmdlets",
            "Detect use of 'mail' or 'mailx' commands for deletion of emails",
            "Correlate deletions with known phishing or C2 activities",
            "Monitor mail flow rule changes affecting all users"
        ],
        "apt": ["Turla", "Cobalt Kitty"],
        "spl_query": [
            "index=exchange_logs sourcetype=ms:exchange:powershell command=\"*Remove-MailboxExportRequest*\" \n| stats count by user, host",
            "index=sysmon parent_process_name=\"powershell.exe\" CommandLine=\"*Remove-MailboxExportRequest*\" \n| table _time, user, CommandLine",
            "index=linux_logs command=\"mail* -d*\" \n| stats count by user, host, command"
        ],
        "hunt_steps": [
            "Search for mailbox export and removal commands in Exchange logs",
            "Check for abnormal transport rules affecting spam or malicious email",
            "Correlate mailbox manipulation with user access logs or unusual login locations",
            "Scan endpoints for use of AppleScript interacting with mail APIs"
        ],
        "expected_outcomes": [
            "Evidence of mailbox exports and deletions removed from logs",
            "Emails tied to phishing or C2 activity missing from mailboxes",
            "Reduced visibility of suspicious mail transport"
        ],
        "false_positive": "Legitimate IT administrators may use mailbox export/removal tools during audits or migrations. Cross-check with ticketing systems and admin change logs.",
        "clearing_steps": [
            "Remove-MailboxExportRequest -Identity <export ID>",
            "Get-MailboxExportRequest | Remove-MailboxExportRequest",
            "rm ~/Library/Mail/* -rf (macOS)",
            "mail -d <messageID> (Linux mail deletion)"
        ],
        "mitre_mapping": [
            {"tactic": "collection", "technique": "T1114", "example": "Collection of email data prior to deletion"},
            {"tactic": "exfiltration", "technique": "T1048", "example": "Exfiltrated emails before clearing export logs"},
            {"tactic": "defense-evasion", "technique": "T1566", "example": "Phishing emails deleted post-delivery"}
        ],
        "watchlist": [
            "High volume of mailbox deletion commands",
            "Transport rule updates across org",
            "PowerShell script blocks tied to Exchange mail modules"
        ],
        "enhancements": [
            "Enable mailbox auditing in Microsoft 365 or Exchange",
            "Alert on use of Remove-* cmdlets without change control",
            "Restrict mail API usage to specific service accounts only"
        ],
        "summary": "Technique involves clearing mailbox data and related logs to hide evidence of malicious activity, particularly after phishing, C2, or exfiltration via email.",
        "remediation": "Reinforce mailbox logging and PowerShell command auditing. Monitor admin behavior and restrict unnecessary use of mail export or delete tools.",
        "improvements": "Implement real-time monitoring for email rule changes and API interactions. Use retention policies that preserve logs even after manual deletions.",
        "mitre_version": "16.1"
    }
