def get_content():
    return {
        "id": "T1550",
        "url_id": "attack-pattern--51a14c76-dd3b-440b-9c20-2bf91d25a814",
        "title": "Use Alternate Authentication Material",
        "description": "Adversaries may use alternate authentication material, such as password hashes, Kerberos tickets, and application access tokens, in order to move laterally within an environment and bypass normal system access controls. Authentication processes generally require a valid identity (e.g., username) along with one or more authentication factors (e.g., password, pin, physical smart card, token generator, etc.). Alternate authentication material is legitimately generated by systems after a user or application successfully authenticates by providing a valid identity and the required authentication factor(s). Caching alternate authentication material allows the system to verify an identity has successfully authenticated without asking the user to reenter authentication factor(s). Because the alternate authentication must be maintained by the system—either in memory or on disk—it may be at risk of being stolen through credential access techniques. By stealing alternate authentication material, adversaries are able to bypass system access controls and authenticate to systems without knowing the plaintext password or any additional authentication factors.",
        "tags": ["credential-theft", "lateral-movement", "token-abuse", "kerberos", "password-hash"],
        "tactic": "Defense Evasion, Lateral Movement",
        "protocol": "varied",
        "os": "Windows, SaaS, IaaS, Identity Provider, Office Suite, Containers",
        "tips": "Ensure detection covers both memory-based and disk-based credential artifacts, including Kerberos tickets and web tokens. Use EDR with memory scanning to detect suspicious use of stolen tokens.",
        "data_sources": "Active Directory, Application Logs, Logon Sessions, Web Credential Usage",
        "log_sources": [
            {"type": "Active Directory", "source": "Credential Request", "destination": "Authentication Log"},
            {"type": "Application Log", "source": "Token Generation", "destination": "Authorization Server"},
            {"type": "Logon Session", "source": "Authentication Service", "destination": "Session Manager"},
            {"type": "Web Credential", "source": "Browser or App", "destination": "Cloud Service"}
        ],
        "source_artifacts": "Token issuance events, Kerberos TGTs, NTLM hashes",
        "destination_artifacts": "Authenticated sessions established without password input",
        "detection_methods": [
            "Audit login sessions for unexpected usage patterns",
            "Correlate VPN and physical entry logs with active logins",
            "Detect token reuse from geographically inconsistent IPs"
        ],
        "apt": [
            "APT29", "NOBELIUM", "IRON RITUAL"
        ],
        "spl_query": [
            "index=wineventlog EventCode=4624 LogonType=3\n| stats count by Account_Name, Workstation_Name, IpAddress\n| where count > 5",
            "index=o365 sourcetype=\"o365:management\" Operation=UserLoggedIn\n| stats dc(ClientIP) by UserId\n| where dc(ClientIP) > 3"
        ],
        "hunt_steps": [
            "Search for concurrent logins of the same user across multiple systems",
            "Review token issuance logs and compare IP origin",
            "Identify long-lived sessions using access tokens"
        ],
        "expected_outcomes": [
            "Detection of unauthorized token use across endpoints",
            "Revealing abnormal login patterns or persistence via tokens"
        ],
        "false_positive": "Shared service accounts or SSO environments may generate similar login patterns across systems.",
        "clearing_steps": [
            "Revoke compromised tokens from IdP portal",
            "Reset account credentials and enforce MFA",
            "Purge Kerberos tickets and clear token cache"
        ],
        "mitre_mapping": [
            {"tactic": "Defense Evasion", "technique": "T1550", "example": "Use of stolen Kerberos TGT to authenticate without password"},
            {"tactic": "Lateral Movement", "technique": "T1550", "example": "Using a pass-the-hash technique to access another host"}
        ],
        "watchlist": [
            "Users with repeated logins from different IPs",
            "Accounts generating excessive token issuance events"
        ],
        "enhancements": [
            "Integrate with behavioral analytics to profile user login patterns",
            "Enable real-time token revocation alerts"
        ],
        "summary": "This technique allows adversaries to authenticate using stolen tokens or hashes instead of passwords, enabling stealthy lateral movement and privilege abuse.",
        "remediation": "Force credential and token refresh, implement short token lifetimes, and monitor for anomalous authentication behavior across environments.",
        "improvements": "Adopt token binding, use signed JWTs with limited scope, and ensure strict monitoring of authentication material in memory and on disk.",
        "mitre_version": "16.1"
    }